### ISSUE TITLE
Metadata migration

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/integration-service#34] opened 2022-08-08 09:17 UTC
### Acceptance criteria

There are mechanisms to automate pulling of metadata for an organisation on integration-service. and pushing them to another organisation/implementation. This will be used to migrate changes from one organisation to another

### Tech notes
- Start using uuids

**Comment by petmongrels** [comment] 2022-08-16 08:40
For Exotel integration, all of the data is set up in the migration script. So this story can be played later.

**Comment by himeshr** [comment] 2023-07-26 06:12
Closed as duplicate of #73

**Closed by himeshr** 2023-07-26 06:12 UTC
