### ISSUE TITLE
Error Records creation is missing the integration system value in certain cases

### ISSUE THREAD

**Issue by petmongrels** [avniproject/integration-service#70] opened 2023-06-12 06:49 UTC
example: 
https://gist.github.com/angshu/541586bf7b5abb8649d94c5379d21894

do check if it is missed out elsewhere too.

**Comment by himeshr** [comment] 2023-09-15 05:59
Resolved this as part of an earlier commit.. 
ec01673172ed9a8735e4d1d8841c54d07dd77450

fix done in AvniBahmniErrorService.java

Duplicate of avniproject/goonj#73

**Closed** 2023-09-15 05:59 UTC
Labels: bug, Analysis Complete
